name: ng-my-page-flow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm install
          npm run generate

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: build
        run: |
          npm install
          npm run generate
          ls -l
      - name: deploy
        run: |
          ls -l
          npm run deploy:only -- --token=&FIREBASE_TOKEN
        env:
          $FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
