name: ng-my-page-pull-request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ./
      - run: |
          npm install
          npm run generate
          ls -l
          npm run deploy:only -- --token=${{secrets.FIREBASE_TOKEN}}
