name: ng-my-page-pull-request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint
      # build通ること確認
      - name: build
        timeout-minutes: 5
        run: npm run build:prod

      - name: deploy-dry-run
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          npm run build -- --configuration production --aot
#          npx angular-cli-ghpages --dry-run --dir=public/browser --name="${USER_NAME}" --email="${EMAIL}" --repo=https://github.com/Tetsuya-Minase/Tetsuya-Minase.github.io.git --branch=gh-pages
          npm run deploy -- --dry-run --dir=public/browser --name="${USER_NAME}" --email="${EMAIL}" --repo=https://github.com/Tetsuya-Minase/Tetsuya-Minase.github.io.git --branch=gh-pages

      - name: notice-failure
        if: failure()
        run: |
          curl -XPOST -H "Content-Type: application/json" -XPOST -d "{\"content\": \"${{ secrets.DISCORD_MENTION }} deploy failure :umbrella:\",\"embeds\": [{\"title\": \"build detail\", \"color\": 14427686, \"fields\": [{\"name\": \"repository\",\"value\": \"$GITHUB_REPOSITORY\"}, {\"name\": \"action url\", \"value\": \"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}]}]}" ${{ secrets.DISCORD_URL }}
      - name: notice-success
        if: success()
        run: |
          curl -XPOST -H "Content-Type: application/json" -XPOST -d "{\"content\": \"deploy success :sunny:\",\"embeds\": [{\"title\": \"build detail\", \"color\": 1096065, \"fields\": [{\"name\": \"repository\",\"value\": \"$GITHUB_REPOSITORY\"}, {\"name\": \"action url\", \"value\": \"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}]}]}" ${{ secrets.DISCORD_URL }}

