name: deploy-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install and setup config
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          publish_branch: master

      - name: slack-notice-failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: 'ci-info'
          SLACK_COLOR: '#3278BD'
          SLACK_MESSAGE: 'deploy failure. :umbrella_with_rain_drops:'
          SLACK_TITLE: inform-weather-forcast
          SLACK_USERNAME: ci_bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_HOOK }}

      - name: slack-notice-success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: 'ci-info'
          SLACK_COLOR: '#3278BD'
          SLACK_MESSAGE: 'deploy success. :sunny:'
          SLACK_TITLE: inform-weather-forcast
          SLACK_USERNAME: ci_bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_HOOK }}
